name: Dev.to Post Workflow
on:
 schedule:
  - cron: '59 23 * * *'
 workflow_dispatch:

jobs:
 update-readme-with-blog:
  name: Update this repo's README with latest blog posts
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: gautamkrishnar/blog-post-workflow@master
     with:
      feed_list: 'https://dev.to/feed/bdfd2005'
      date_format: 'mmm d, yyyy'
      max_post_count: 3
      template: '
       <table>
       <tr>
       <td>
       <a href="$url">
       $title
       </a>
       </td>
       $newline
       <td>
       Post Date:$date
       </td>
       </tr>
       </table>'
